/* Business directory.

   A curated directory of Niwot businesses, checked against business-owned
   and community sources: each business's own website where it publishes
   one, the Niwot Business Association's directory at niwot.com, and dated
   reports in the Left Hand Valley Courier (lhvc.com). Nothing here is
   inferred — a field is present only where a source stated it.

   The record shape, the validation rules and the freshness threshold are
   documented in lib/directory.js. The short version:

   - `verifiedAt` is the day that particular row was last checked, and the
     page shows it row by row. The rows dated 2026-09-08 were compiled on the
     first pass; the rows dated 2026-09-09 were re-checked or added in the
     September 2026 audit; the rows dated 2026-09-10 were changed after the
     launch audit's sweep of every external link (two rows held back, two
     rerouted to the Association directory — each says why in its note).
     Three destinations the sweep could not settle by machine are left as
     they were and need a person: sliferfrontrange.com timed out, and
     niwotlaw.com and thegardengatecafe.com answered 403 to the automated
     client, which is usually bot-blocking rather than a dead site.
   - `status` decides what is published. Only `active` and
     `temporarily_closed` rows render. `closed` and `unverified` rows stay
     here as the record of what was checked and why, with an `editorialNote`
     that is never published.
   - `address` is the street address as published, with suite numbers only
     where a single source gives them unambiguously. `sharesAddress: true`
     marks an address knowingly shared with another row — a counter inside
     Niwot Market, two suites in one building — so the duplicate-address
     check can tell that from one business replacing another.
   - Phone numbers are deliberately not reproduced. They change more often
     than anything else on a listing, so every row links out instead.
   - `description` is omitted where no source described the business. A row
     with a name, a category and a place is still a useful row; an invented
     sentence is not.
   - Food and drink rows carry the facets the restaurant guide at
     /restaurants/ renders: `guide` (which group it files under), `cuisine`,
     `kind`, `patio` and `serves`. Every one of them is condensed from that
     row's own `description`, which came from the source named in
     `sourceUrl` — none is inferred from the kind of business it is. Where
     the source says nothing about outdoor seating or about which meals are
     served, the facet is absent and the guide shows nothing rather than
     "no". `menuUrl` and `priceRange` are in the schema and are not yet set
     on any row: no source read so far publishes a menu page separate from
     the business's own site, or a price range. Neither is estimated.

   Closures recorded in earlier passes and dropped rather than archived:
   Bell, Book, Candle & Coffee (lease ended May 2018), The Wandering
   Jellyfish Bookshop (December 2023), Farow (2025), Few of a Kind Vintage +
   Mercantile (April 25, 2026), Pie Dog Pizza, The Little Shop and Niwot
   Veterinary Clinic. Lefty's Gourmet Pizza left 364 Second Avenue for
   Longmont and trades there as Niwot Pizza.

   Coverage is not a claim of completeness. The Association directory was
   searched rather than crawled end to end, and a sole trader who keeps no
   public listing will not appear. The page says so and invites the ones that
   are missing. */
import { CATEGORIES, assertValidListings, publishListings, FRESHNESS_DAYS } from '../../lib/directory.js';

/* The Association's own directory. Rows without a website of their own link
   here or to their Association listing, where the current hours live. */
const association = 'https://niwot.com/';

const FIRST_PASS = '2026-09-08';
const AUDIT = '2026-09-09';
/* The September 10, 2026 launch audit's sweep of every external link. */
const LINK_SWEEP = '2026-09-10';

const records = [
  /* ---- Restaurants & Bars ---- */
  {
    slug: 'niwot-tavern',
    name: 'Niwot Tavern',
    category: 'restaurants-bars',
    area: 'Cottonwood Square',
    address: '7960 Niwot Road',
    sharesAddress: true,
    description: 'Neighborhood tavern with a covered patio on the corner, beside the bear sculptures.',
    website: 'https://www.niwottavern.com/',
    guide: 'sit-down',
    cuisine: 'American — neighborhood tavern',
    kind: 'Sit-down and bar',
    patio: 'Covered patio on the corner, beside the bear sculptures',
    sourceUrl: 'https://www.niwottavern.com/',
    schemaType: 'Restaurant',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'raza-fresa',
    name: 'Raza Fresa Mexican Kitchen',
    category: 'restaurants-bars',
    area: 'Cottonwood Square',
    address: '7960 Niwot Road, Suite 11D',
    description: 'Mexican kitchen with umbrella-shaded patio seating alongside the square.',
    website: 'https://razafresa.com/',
    guide: 'sit-down',
    cuisine: 'Mexican',
    kind: 'Sit-down',
    patio: 'Umbrella-shaded patio seating alongside the square',
    sourceUrl: 'https://razafresa.com/',
    schemaType: 'Restaurant',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'cimminis',
    name: 'Cimmini’s Italian Restaurant',
    category: 'restaurants-bars',
    area: 'Old Town, 300 block',
    address: '300 Second Avenue',
    description: 'Italian cooking made from scratch, on the 300 block with a heated front patio. Open since January 2022.',
    website: 'https://cimminisniwot.com/',
    guide: 'sit-down',
    cuisine: 'Italian',
    kind: 'Sit-down',
    patio: 'Heated front patio on the 300 block',
    sourceUrl: 'https://cimminisniwot.com/',
    schemaType: 'Restaurant',
    verifiedAt: AUDIT,
    status: 'active',
  },
  {
    slug: 'fortezza-ristorante',
    name: 'Fortezza Ristorante',
    category: 'restaurants-bars',
    address: '7916 Niwot Road',
    description: 'Northern Italian steakhouse: house-made pasta, Wagyu steaks and a long wine list. Opened August 2025.',
    website: 'https://fortezzaristorante.com/',
    guide: 'sit-down',
    cuisine: 'Northern Italian steakhouse',
    kind: 'Sit-down',
    sourceUrl: 'https://fortezzaristorante.com/',
    schemaType: 'Restaurant',
    verifiedAt: AUDIT,
    status: 'active',
  },
  {
    slug: '1914-house',
    name: '1914 House',
    category: 'restaurants-bars',
    area: 'Old Town, Second Avenue',
    address: '121 Second Avenue',
    description: 'Contemporary American cooking in a two-story historic building.',
    sourceUrl: 'https://www.lhvc.com/story/2026/06/24/news/taverna-laudisio-opens-in-the-former-1914-house-location/12188.html',
    verifiedAt: AUDIT,
    status: 'closed',
    editorialNote:
      'Closed. The Left Hand Valley Courier (April 15 and June 24, 2026) reports that the owner ran 1914 House at 121 Second Avenue until 2024 and now leases the building to Taverna Laudisio, which opened June 18, 2026; Yelp marks the restaurant closed. Its former website was http-only and is no longer linked. Kept for the record; not published.',
  },
  {
    slug: 'taverna-laudisio',
    name: 'Taverna Laudisio',
    category: 'restaurants-bars',
    area: 'Old Town, Second Avenue',
    address: '121 Second Avenue',
    postalCode: '80544',
    description: 'Simple, homey Italian cooking from the Laudisio family, in the two-story historic building that housed 1914 House. Opened June 2026.',
    website: 'https://tavernalaudisio.com/',
    guide: 'sit-down',
    cuisine: 'Italian',
    kind: 'Sit-down',
    sourceUrl: 'https://www.lhvc.com/story/2026/06/24/news/taverna-laudisio-opens-in-the-former-1914-house-location/12188.html',
    schemaType: 'Restaurant',
    verifiedAt: AUDIT,
    status: 'active',
    editorialNote:
      'Added in the September 2026 audit. Address 121 2nd Ave, Niwot, CO 80544 from the restaurant’s own site; opening dates (June 18–20, 2026) and the 1914 House succession from the Courier’s June 24, 2026 report.',
  },
  {
    slug: 'sachi-sushi',
    name: 'Sachi Sushi',
    category: 'restaurants-bars',
    area: 'Inside Niwot Market',
    address: '7980 Niwot Road',
    sharesAddress: true,
    description: 'Japanese kitchen at the back of Niwot Market — sushi through the week and ramen on Sundays. Closed Mondays and Tuesdays.',
    website: 'https://niwotmarket.com/sachi-sushi-1',
    guide: 'quick',
    cuisine: 'Japanese',
    kind: 'Kitchen at the back of Niwot Market',
    serves: 'Sushi through the week and ramen on Sundays; closed Mondays and Tuesdays',
    sourceUrl: 'https://niwotmarket.com/sachi-sushi-1',
    schemaType: 'Restaurant',
    verifiedAt: AUDIT,
    status: 'active',
  },
  {
    slug: 'fans-chinese-cuisine',
    name: 'Fan’s Chinese Cuisine',
    category: 'restaurants-bars',
    area: 'Cottonwood Square',
    address: '7960 Niwot Road, Unit C9',
    description: 'Chinese kitchen in the square: dine in, take out or delivery.',
    guide: 'sit-down',
    cuisine: 'Chinese',
    kind: 'Sit-down, take-out and delivery',
    sourceUrl: association,
    schemaType: 'Restaurant',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'abos-pizza',
    name: 'Abo’s Pizza Niwot',
    category: 'restaurants-bars',
    area: 'Cottonwood Square',
    address: '7960 Niwot Road, Suite B5',
    description: 'New York-style pizza by the slice or the pie, from the Boulder original that started in 1977.',
    website: 'https://abospizza.com/locations/niwot/',
    guide: 'quick',
    cuisine: 'New York-style pizza',
    kind: 'Counter — by the slice or the pie',
    sourceUrl: 'https://abospizza.com/locations/niwot/',
    schemaType: 'Restaurant',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'garden-gate-cafe',
    name: 'The Garden Gate Cafe',
    category: 'restaurants-bars',
    area: 'Cottonwood Square',
    address: '7960 Niwot Road, Unit B4',
    description: 'Breakfast and lunch daily — benedicts, farmhouse plates and Southwest specials.',
    website: 'https://www.thegardengatecafe.com/',
    guide: 'sit-down',
    cuisine: 'American — benedicts, farmhouse plates and Southwest specials',
    kind: 'Sit-down',
    serves: 'Breakfast and lunch daily',
    sourceUrl: 'https://www.thegardengatecafe.com/',
    schemaType: 'Restaurant',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'fritz-family-brewers',
    name: 'Fritz Family Brewers',
    category: 'restaurants-bars',
    address: '6778 N 79th Street',
    description: 'Family-run brewery pouring German-style lagers and ales. Kids and dogs welcome.',
    website: 'https://www.fritzfamilybrewers.com/',
    guide: 'bars-breweries',
    cuisine: 'German-style lagers and ales',
    kind: 'Family-run brewery; kids and dogs welcome',
    sourceUrl: 'https://www.fritzfamilybrewers.com/',
    schemaType: 'Brewery',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'the-wheel-house',
    name: 'The Wheel House',
    category: 'restaurants-bars',
    area: 'Old Town, Second Avenue',
    address: '101 Second Avenue, Suite B',
    postalCode: '80544',
    description: 'Neighborhood bar and taproom with a back patio and live music. Opened September 2020; its own kitchen opened in February 2026.',
    website: 'https://www.niwotwheelhouse.com/',
    guide: 'bars-breweries',
    cuisine: 'Bar and taproom, with a kitchen of its own since February 2026',
    kind: 'Bar with live music',
    patio: 'Back patio',
    sourceUrl: 'https://www.niwotwheelhouse.com/contact',
    schemaType: 'BarOrPub',
    verifiedAt: AUDIT,
    status: 'active',
    editorialNote:
      'Address sources disagree. Published per the business’s own site, which gives 101 2nd Ave, Suite B, Niwot, CO 80544 — the same street number the Courier reported when the bar opened on September 17, 2020, and the one third-party listings carry. The Business Association listing (niwot.com/the-wheel-house-niwot/) shows 124 2nd Ave. This guide previously said 300 Second Avenue, which no source supports. Only the business-site address is published; re-check on the next pass.',
  },
  {
    slug: 'la-musette',
    name: 'La Musette',
    category: 'restaurants-bars',
    area: 'Murray Street, behind The Wheel House',
    description: 'Farm-to-table food truck. The menu changes with what is in season.',
    sourceUrl: 'https://www.lhvc.com/story/2023/07/19/news/familiar-face-skyla-at-la-musette-food-truck/8166.html',
    verifiedAt: AUDIT,
    status: 'unverified',
    editorialNote:
      'Held back in the September 2026 audit. The truck was parked behind The Wheel House from August 2021 (Courier, October 13, 2021 and July 19, 2023), but the operator’s Instagram now describes weekly dinner drop-offs in Niwot and Boulder and says it is no longer a Niwot-based truck. Neither state could be confirmed against a dated source, so the row is not published until one is.',
  },
  {
    slug: 'niwot-market-deli',
    name: 'Niwot Market Deli',
    category: 'restaurants-bars',
    area: 'Inside Niwot Market',
    address: '7980 Niwot Road',
    sharesAddress: true,
    description: 'Deli counter inside the market: breakfast burritos, made-to-order sandwiches and a soup bar.',
    website: 'https://niwotmarket.com/deli',
    guide: 'quick',
    cuisine: 'Deli — breakfast burritos, made-to-order sandwiches and a soup bar',
    kind: 'Counter inside Niwot Market',
    sourceUrl: 'https://niwotmarket.com/deli',
    schemaType: 'Restaurant',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'subway',
    name: 'Subway',
    category: 'restaurants-bars',
    area: 'Cottonwood Square',
    address: '7960 Niwot Road, Unit B10',
    description: 'Independently owned franchise of the sandwich chain, in the square.',
    website: 'https://restaurants.subway.com/united-states/co/niwot/7960-niwot-rd',
    guide: 'quick',
    cuisine: 'Sandwiches',
    kind: 'Counter — independently owned franchise',
    sourceUrl: 'https://restaurants.subway.com/united-states/co/niwot/7960-niwot-rd',
    schemaType: 'Restaurant',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },

  /* ---- Coffee, Bakery & Sweets ---- */
  {
    slug: 'old-oak-coffeehouse',
    name: 'The Old Oak Coffeehouse',
    category: 'coffee-bakery',
    area: 'Old Town, Second Avenue',
    address: '136 Second Avenue',
    description: 'Specialty coffee, house-made baked goods and panini, seven days a week.',
    website: 'https://www.theoldoakcoffeehouse.com/',
    guide: 'coffee-sweets',
    cuisine: 'Specialty coffee, house-made baked goods and panini',
    kind: 'Coffeehouse',
    serves: 'Seven days a week',
    sourceUrl: 'https://www.theoldoakcoffeehouse.com/',
    schemaType: 'CafeOrCoffeeShop',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'winot-coffee-company',
    name: 'WiNot Coffee Company',
    category: 'coffee-bakery',
    area: 'Cottonwood Square',
    address: '7960 Niwot Road, Unit D13',
    description: 'Independent, family-owned coffeehouse on the square, established 2007.',
    guide: 'coffee-sweets',
    cuisine: 'Coffee',
    kind: 'Independent, family-owned coffeehouse',
    sourceUrl: 'https://niwot.com/listing/winot-coffee-company/',
    schemaType: 'CafeOrCoffeeShop',
    verifiedAt: AUDIT,
    status: 'active',
  },
  {
    slug: 'emory-janes-coffee-co',
    name: 'Emory Jane’s Coffee Co.',
    category: 'coffee-bakery',
    area: 'Mobile, around Niwot',
    description: 'Mobile espresso bar pouring coffee, tea and pastries from a restored 1969 Dodge A100 van. Where it parks changes, so check the operator’s schedule.',
    website: 'https://www.emoryjanescoffeeco.com/',
    guide: 'coffee-sweets',
    cuisine: 'Coffee, tea and pastries',
    kind: 'Mobile espresso bar in a restored 1969 Dodge A100 van',
    serves: 'Where it parks changes; the operator publishes the schedule',
    sourceUrl: 'https://niwot.com/listing/emory-janes-coffee-co/',
    schemaType: 'CafeOrCoffeeShop',
    verifiedAt: AUDIT,
    status: 'active',
    editorialNote:
      'Added in the September 2026 audit from the Business Association listing and the operator’s own site. It has no fixed address, so none is published.',
  },
  {
    slug: 'love-ice-cream',
    name: 'Love Ice Cream',
    category: 'coffee-bakery',
    area: 'Old Town, Second Avenue',
    address: '240 Second Avenue',
    postalCode: '80544',
    sharesAddress: true,
    description: 'Small-batch ice cream shop on the 200 block, with dairy-free flavors among the dozen or so on offer. Opened September 2024.',
    website: 'https://www.loveicecream.co/',
    guide: 'coffee-sweets',
    cuisine: 'Small-batch ice cream, dairy-free flavors among them',
    kind: 'Shop on the 200 block',
    sourceUrl: 'https://niwot.com/listing/love-ice-cream/',
    schemaType: 'IceCreamShop',
    verifiedAt: AUDIT,
    status: 'active',
    editorialNote:
      'Added in the September 2026 audit. Address 240 2nd Avenue, Niwot, CO 80544 from the Business Association listing; opening (September 21, 2024) from the Courier. Sources give 240 Second Avenue for Blessings Day Spa as well; the Courier places the shop next door to Blessings, in the former Seven Wealth office, so both rows carry sharesAddress.',
  },

  /* ---- Grocery & Provisions ---- */
  {
    slug: 'niwot-market',
    name: 'Niwot Market',
    category: 'grocery-provisions',
    address: '7980 Niwot Road',
    sharesAddress: true,
    description: 'The independent grocery, in business since 2002: produce, deli, prepared foods and pet supplies.',
    website: 'https://niwotmarket.com/',
    guide: 'provisions',
    kind: 'Independent grocery — produce, deli, prepared foods and pet supplies',
    sourceUrl: 'https://niwotmarket.com/',
    schemaType: 'GroceryStore',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'niwot-liquor',
    name: 'Niwot Liquor Store',
    category: 'grocery-provisions',
    area: 'Old Town, Second Avenue',
    address: '361 Second Avenue',
    guide: 'provisions',
    kind: 'Liquor store',
    sourceUrl: 'https://niwot.com/listing/niwot-liquor/',
    schemaType: 'LiquorStore',
    verifiedAt: AUDIT,
    status: 'active',
  },

  /* ---- Shops & Gifts ---- */
  {
    slug: 'little-bird',
    name: 'Little Bird',
    category: 'shops-gifts',
    area: 'Old Town, Second Avenue',
    address: '112 Second Avenue',
    description: 'Women’s clothing, handmade jewelry, locally made body care and art.',
    sourceUrl: 'https://niwot.com/listing/little-bird/',
    schemaType: 'Store',
    verifiedAt: AUDIT,
    status: 'active',
  },
  {
    slug: 'wise-buys-antiques',
    name: 'Wise Buys Antiques',
    category: 'shops-gifts',
    area: 'Old Town, Second Avenue',
    address: '190 Second Avenue',
    description: 'Five thousand square feet of collectibles from the 1800s onward, plus furniture refinishing and repair.',
    sourceUrl: 'https://niwot.com/listing/wise-buys-antiques/',
    schemaType: 'Store',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'niwot-jewelry-gifts',
    name: 'Niwot Jewelry & Gifts',
    category: 'shops-gifts',
    area: 'Old Town, 300 block',
    address: '300 Second Avenue, Suite 102',
    sourceUrl: 'https://niwot.com/listing/niwot-jewelry-gifts/',
    schemaType: 'JewelryStore',
    verifiedAt: AUDIT,
    status: 'active',
  },
  {
    slug: 'inkberry-books',
    name: 'Inkberry Books',
    category: 'shops-gifts',
    area: 'Cottonwood Square',
    address: '7960 Niwot Road, Suite B3',
    description: 'Independent bookshop, open since 2018: new, gently used and out-of-print books, with art by Boulder County artists each month.',
    sourceUrl: 'https://niwot.com/listing/inkberry-books/',
    schemaType: 'BookStore',
    verifiedAt: AUDIT,
    status: 'active',
  },
  {
    slug: 'fly-away-home',
    name: 'Fly Away Home',
    category: 'shops-gifts',
    area: 'Cottonwood Square',
    address: '7960 Niwot Road',
    sharesAddress: true,
    description: 'Home decor, cozy knits, accessories and gifts.',
    website: 'https://www.flyawayhomedecor.com/',
    sourceUrl: 'https://www.flyawayhomedecor.com/',
    schemaType: 'Store',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'the-nook',
    name: 'The Nook',
    category: 'shops-gifts',
    area: 'Inside Niwot Market',
    address: '7980 Niwot Road',
    sharesAddress: true,
    description: 'Home decor and gifts tucked into the market, run by the same owner since 2019.',
    website: 'https://niwotmarket.com/the-nook',
    sourceUrl: 'https://niwotmarket.com/the-nook',
    schemaType: 'Store',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'belle-terre-floral',
    name: 'Belle Terre Floral',
    category: 'shops-gifts',
    area: 'Cottonwood Square, and inside Niwot Market',
    address: '7960 Niwot Road',
    sharesAddress: true,
    description: 'Florist, with a second counter inside the market.',
    sourceUrl: 'https://niwot.com/listing/belle-terre-floral/',
    schemaType: 'Florist',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'niwot-wheel-works',
    name: 'Niwot Wheel Works',
    category: 'shops-gifts',
    area: 'Cottonwood Square',
    address: '7960 Niwot Road, Unit C10',
    description: 'Bike shop: sales, rentals, tune-ups and apparel. In the south-west corner of the square, next to Fan’s, since March 2025.',
    website: 'https://www.niwotwheelworks.com/',
    sourceUrl: 'https://www.niwotwheelworks.com/',
    schemaType: 'BikeStore',
    verifiedAt: AUDIT,
    status: 'active',
  },
  {
    slug: 'murray-street-flowers',
    name: 'Murray Street Flowers',
    category: 'shops-gifts',
    area: 'Old Town, at First Avenue and Murray Street',
    address: '100 Murray Street',
    description: 'Small flower grower with a self-serve flower cart at the corner of First Avenue and Murray Street, across from the children’s park. The cart is out Fridays and Saturdays from April to October.',
    website: 'https://www.murraystreetflowers.com/',
    sourceUrl: 'https://www.murraystreetflowers.com/get-in-touch',
    schemaType: 'Florist',
    verifiedAt: AUDIT,
    status: 'active',
    editorialNote:
      'Added in the September 2026 audit from the grower’s own site and the Courier’s business profile of June 4, 2025.',
  },

  /* ---- Arts & Makers ---- */
  {
    slug: 'osmosis-gallery',
    name: 'Osmosis Gallery',
    category: 'arts-makers',
    area: 'Old Town, Second Avenue',
    address: '290 Second Avenue',
    sharesAddress: true,
    description: 'Contemporary gallery in a renovated 1910 brick building, showing more than forty Colorado artists.',
    website: 'https://www.osmosisartgallery.com/',
    sourceUrl: 'https://www.osmosisartgallery.com/',
    schemaType: 'ArtGallery',
    verifiedAt: AUDIT,
    status: 'active',
  },
  {
    slug: 'pebble-art-jewelry',
    name: 'Pebble Art Jewelry',
    category: 'arts-makers',
    area: 'Cottonwood Square, at Niwot Market',
    address: '7980 Niwot Road',
    sharesAddress: true,
    description: 'Handmade jewelry, at Niwot Market.',
    sourceUrl: 'https://niwot.com/listing/pebble-art-jewelry/',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },

  /* ---- Health & Wellness ---- */
  {
    slug: 'left-hand-animal-hospital',
    name: 'Left Hand Animal Hospital',
    category: 'health-wellness',
    area: 'Old Town, Franklin Street',
    address: '304 Franklin Street',
    description: 'Veterinary practice, weekdays only.',
    website: 'https://lefthandanimalhospital.com/',
    sourceUrl: 'https://lefthandanimalhospital.com/',
    schemaType: 'VeterinaryCare',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'niwot-natural-medicine',
    name: 'Niwot Natural Medicine',
    category: 'health-wellness',
    area: 'Old Town, Second Avenue',
    address: '165 Second Avenue',
    sourceUrl: 'https://niwot.com/listing/niwot-natural-medicine-2/',
    schemaType: 'MedicalBusiness',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'ohm-physical-therapy',
    name: 'OHM Physical Therapy',
    category: 'health-wellness',
    area: 'Cottonwood Square',
    address: '7960 Niwot Road',
    sharesAddress: true,
    sourceUrl: 'https://niwot.com/listing/ohm/',
    schemaType: 'MedicalBusiness',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'dignity-counseling',
    name: 'Dignity Counseling and Wellness',
    category: 'health-wellness',
    area: 'Old Town, Franklin Street',
    address: '210 Franklin Street',
    sourceUrl: 'https://niwot.com/listing/dignity-counseling-and-wellness/',
    schemaType: 'MedicalBusiness',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'western-wellness-chiropractic',
    name: 'Western Wellness Chiropractic',
    category: 'health-wellness',
    area: 'Old Town, Second Avenue',
    address: '198 Second Avenue',
    description: 'Chiropractic practice specializing in spinal decompression. Opened in Niwot in 2024.',
    sourceUrl: association,
    schemaType: 'MedicalBusiness',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'chill-cryotherapy',
    name: 'Chill Cryotherapy & Recovery',
    category: 'health-wellness',
    area: 'Old Town, Second Avenue',
    address: '198 Second Avenue, Unit D',
    description: 'Cryotherapy, compression therapy and muscle recovery.',
    website: 'https://chill303.com/',
    sourceUrl: 'https://chill303.com/',
    schemaType: 'HealthAndBeautyBusiness',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'butterfield-wellness',
    name: 'Butterfield Wellness Center',
    category: 'health-wellness',
    address: '8940 Morton Road',
    description: 'Neuromuscular massage therapy — deep tissue work aimed at pain patterns.',
    sourceUrl: association,
    editorialNote:
      'The practice’s own site (butterfieldwellness.com) answered HTTP 502 in the 2026-09-10 link sweep, so the row no longer links to it and points at the Association directory instead. Check the site by hand; if it answers, restore `website` and `sourceUrl`; if it stays down on the next pass, set the row to unverified.',
    schemaType: 'HealthAndBeautyBusiness',
    verifiedAt: LINK_SWEEP,
    status: 'active',
  },
  {
    slug: 'hidden-yoga-studio',
    name: 'The Hidden Yoga Studio',
    category: 'health-wellness',
    area: 'Old Town, Second Avenue',
    address: '361 Second Avenue, Unit 201',
    sourceUrl: association,
    editorialNote:
      'The studio’s own site (thehiddenyogastudio.com) answered HTTP 502 in the 2026-09-10 link sweep, so the row no longer links to it and points at the Association directory instead. Check the site by hand; if it answers, restore `website` and `sourceUrl`; if it stays down on the next pass, set the row to unverified.',
    schemaType: 'HealthAndBeautyBusiness',
    verifiedAt: LINK_SWEEP,
    status: 'active',
  },
  {
    slug: 'una-vida',
    name: 'Una Vida Meditation & Movement',
    category: 'health-wellness',
    area: 'Cottonwood Square',
    description: 'Weekly classes in yoga, meditation and mindful movement, for all levels.',
    website: 'https://www.unavidaniwot.com/',
    sourceUrl: 'https://www.unavidaniwot.com/',
    schemaType: 'HealthAndBeautyBusiness',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'inner-space-healing',
    name: 'Inner Space Healing',
    category: 'health-wellness',
    area: 'Cottonwood Square',
    description: 'Psychotherapists and other practitioners sharing one space. Opened October 2024.',
    sourceUrl: association,
    schemaType: 'MedicalBusiness',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'hannas-herb-shop',
    name: 'Hanna’s Herb Shop',
    category: 'health-wellness',
    area: 'Cottonwood Square',
    address: '7960 Niwot Road, Suite D15',
    description: 'Herbal apothecary, in Niwot since November 2025 after decades in Boulder. Next door to WiNot Coffee.',
    website: 'https://www.hannasherbshop.com/',
    sourceUrl: 'https://www.lhvc.com/story/2025/11/19/news/hannas-herb-shop-begins-new-chapter-in-niwot/11346.html',
    schemaType: 'Store',
    verifiedAt: AUDIT,
    status: 'active',
  },
  {
    slug: 'alchemy-lounge',
    name: 'The Alchemy Lounge',
    category: 'health-wellness',
    area: 'Old Town',
    description: 'Bodywork sessions and women’s circles.',
    sourceUrl: association,
    schemaType: 'HealthAndBeautyBusiness',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'ola-chiropractic',
    name: 'Ola Chiropractic and Wellness',
    category: 'health-wellness',
    area: 'Old Town, Second Avenue',
    address: '263 Second Avenue, Suite 106B',
    postalCode: '80544',
    description: 'Chiropractic and wellness practice run by two chiropractors. Opened on Second Avenue in November 2025.',
    website: 'https://www.olachiropracticwellness.com/',
    sourceUrl: 'https://www.lhvc.com/story/2025/11/12/news/ola-chiropractic-and-wellness-opens-on-second-avenue/11312.html',
    schemaType: 'MedicalBusiness',
    verifiedAt: AUDIT,
    status: 'active',
    editorialNote:
      'Added in the September 2026 audit from the Association listing (niwot.com/listing/ola), the practice’s booking page (263 2nd Ave, Suite 106B, 80544) and the Courier’s opening report.',
  },
  {
    slug: 'niwot-dental',
    name: 'Niwot Dental',
    category: 'health-wellness',
    address: '6800 N 79th Street, Suite 203',
    description: 'Family dental practice: preventative, restorative and cosmetic dentistry. Weekdays.',
    website: 'https://www.niwotdental.com/',
    sourceUrl: 'https://niwot.com/listing/niwot-dental/',
    schemaType: 'Dentist',
    verifiedAt: AUDIT,
    status: 'active',
    editorialNote: 'Added in the September 2026 audit from the Association listing and the practice’s own contact page.',
  },
  {
    slug: 'niles-family-dentistry',
    name: 'Niles Family Dentistry',
    category: 'health-wellness',
    area: 'Old Town, Second Avenue',
    address: '364 Second Avenue',
    postalCode: '80503',
    description: 'General and family dentistry on the 300 block.',
    website: 'https://www.nilesfamilydentistry.com/',
    sourceUrl: 'https://www.nilesfamilydentistry.com/contact',
    schemaType: 'Dentist',
    verifiedAt: AUDIT,
    status: 'active',
    editorialNote:
      'Added in the September 2026 audit. Published per the practice’s own contact page (364 2nd Ave, 80503). Some third-party listings still show 136 2nd Ave #101; the practice site is treated as primary.',
  },
  {
    slug: 'healing-collective',
    name: 'The Healing Collective',
    category: 'health-wellness',
    address: '6800 N 79th Street, Suite 202',
    description: 'Functional medicine practice. Weekday mornings and early afternoons.',
    sourceUrl: 'https://niwot.com/listing/healing-collective-the/',
    schemaType: 'MedicalBusiness',
    verifiedAt: AUDIT,
    status: 'active',
    editorialNote: 'Added in the September 2026 audit from the Association listing; the practice publishes no site of its own, so the row links to the listing.',
  },

  /* ---- Beauty & Personal Care ---- */
  {
    slug: 'blessings-day-spa',
    name: 'Blessings Day Spa & Skincare Boutique',
    category: 'beauty-personal-care',
    area: 'Old Town, Second Avenue',
    address: '240 Second Avenue',
    sharesAddress: true,
    description: 'Facials, lash services and advanced aesthetics.',
    website: 'https://www.niwotblessings.com/',
    sourceUrl: 'https://www.niwotblessings.com/',
    schemaType: 'DaySpa',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'classic-looks',
    name: 'Classic Looks',
    category: 'beauty-personal-care',
    address: '6964 N 79th Street, Unit 6',
    description: 'Full-service salon since 1989 — hair, nails, skincare and barbering.',
    website: 'https://www.classiclooks.net/',
    sourceUrl: 'https://www.classiclooks.net/',
    schemaType: 'BeautySalon',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'niwot-beauty-bar',
    name: 'Niwot Beauty Bar',
    category: 'beauty-personal-care',
    address: '6897 Paiute Avenue',
    description: 'Facials, anti-aging treatments, waxing and makeup.',
    sourceUrl: association,
    schemaType: 'BeautySalon',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: '2nd-nature-hair-lounge',
    name: '2nd Nature Hair Lounge',
    category: 'beauty-personal-care',
    area: 'Old Town, 300 block',
    address: '300 Second Avenue, Suite 101',
    postalCode: '80544',
    description: 'Boutique salon on the 300 block: French haircutting and dimensional color. Weekdays only.',
    website: 'https://2ndnaturehairniwot.com/',
    sourceUrl: 'https://niwot.com/listing/2nd-nature-hair-lounge/',
    schemaType: 'HairSalon',
    verifiedAt: AUDIT,
    status: 'active',
    editorialNote:
      'Added in the September 2026 audit from the Association listing, the salon’s own site and the Courier’s business profile of March 6, 2024. Address 300 2nd Ave #101, Niwot, CO 80544.',
  },

  /* ---- Everyday Services ---- */
  {
    slug: 'johns-dry-cleaners',
    name: 'John’s Dry Cleaners',
    category: 'everyday-services',
    address: '6964 N 79th Street, Unit 5',
    description: 'Dry cleaning and laundry; one of the company’s Boulder-area shops, with pick-up and delivery in Niwot.',
    website: 'https://www.johnsdrycleaners.com/locations/',
    sourceUrl: 'https://www.johnsdrycleaners.com/locations/',
    editorialNote:
      'The shop’s own address page (/6964-n-79th-st/) answered HTTP 404 in the 2026-09-09 pre-launch audit while the browser showed the company homepage, so the row links to the locations page, which lists the Niwot shop at this address. Re-check the address page on the next pass and restore it if it is back.',
    schemaType: 'DryCleaningOrLaundry',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'strohl-electric',
    name: 'Strohl Electric',
    category: 'everyday-services',
    area: 'Niwot',
    description: 'Electrical contractor: full house wiring, remodels, basement finishes and service calls.',
    sourceUrl: 'https://niwot.com/listing/strohl-electric/',
    schemaType: 'Electrician',
    verifiedAt: LINK_SWEEP,
    status: 'unverified',
    editorialNote:
      'Held back after the 2026-09-10 link sweep: the Association listing this row rested on answers HTTP 404, and no other source was found. Restore it when the business can be traced to a current listing or a site of its own.',
  },
  {
    slug: 'sew-fresh-studio',
    name: 'Sew Fresh Studio',
    category: 'everyday-services',
    area: 'Cottonwood Square',
    address: '7960 Niwot Road, Suite B1',
    description: 'Tailoring, alterations and sewing classes. Moved to Cottonwood Square in early 2026 after eleven years on Second Avenue.',
    website: 'https://sewfreshstudio.com/',
    sourceUrl: 'https://www.lhvc.com/story/2026/02/04/news/sew-fresh-makes-a-fresh-start/11627.html',
    schemaType: 'LocalBusiness',
    verifiedAt: AUDIT,
    status: 'active',
    editorialNote: 'Added in the September 2026 audit from the Courier’s February 4, 2026 report on the move and the studio’s own site.',
  },

  /* ---- Professional Services ---- */
  {
    slug: 'warren-moore-rutherford',
    name: 'Warren Moore Rutherford, LLP',
    category: 'professional-services',
    address: '6964 N 79th Street, Suite 3',
    postalCode: '80503',
    description: 'Estate planning, probate, real estate, business and family law. In practice here since 1975; formerly Warren, Carlson & Moore.',
    website: 'https://www.niwotlaw.com/',
    sourceUrl: 'https://www.niwotlaw.com/',
    schemaType: 'LegalService',
    verifiedAt: AUDIT,
    status: 'active',
    editorialNote:
      'Renamed in the September 2026 audit. The firm’s own site and its Association listing now carry the name Warren Moore Rutherford, LLP; this guide had the earlier name Warren, Carlson & Moore, LLP.',
  },
  {
    slug: 'slifer-smith-frampton-niwot',
    name: 'Slifer Smith & Frampton Real Estate, Niwot',
    category: 'professional-services',
    area: 'Old Town, Second Avenue',
    address: '136 Second Avenue, Suite C',
    postalCode: '80503',
    description: 'Residential real estate — the Niwot office of the Front Range brokerage, formerly Colorado Landmark, Realtors.',
    website: 'https://www.sliferfrontrange.com/',
    sourceUrl: 'https://www.sliferfrontrange.com/contact-us/',
    schemaType: 'RealEstateAgent',
    verifiedAt: AUDIT,
    status: 'active',
    editorialNote:
      'Renamed in the September 2026 audit. The Association listing at niwot.com/listing/colorado-landmark-realtors/ now reads Slifer Smith & Frampton, and the brokerage’s own contact page lists the Niwot office at 136 2nd Ave, Suite C. One aggregator marks the office closed; the brokerage’s own site is treated as primary.',
  },
  {
    slug: 'osmosis-architecture',
    name: 'Osmosis Architecture',
    category: 'professional-services',
    area: 'Old Town, Second Avenue',
    address: '290 Second Avenue',
    sharesAddress: true,
    description: 'Residential architecture studio, sharing the 1910 building with the gallery.',
    website: 'https://www.osmosisarchitecture.com/',
    sourceUrl: 'https://www.osmosisarchitecture.com/',
    schemaType: 'ProfessionalService',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'left-hand-valley-courier',
    name: 'Left Hand Valley Courier',
    category: 'professional-services',
    area: 'Niwot',
    description: 'The non-profit weekly covering Niwot and Gunbarrel, delivered free to 6,000 homes and businesses.',
    website: 'https://www.lhvc.com/',
    sourceUrl: 'https://www.lhvc.com/about',
    schemaType: 'NewsMediaOrganization',
    verifiedAt: AUDIT,
    status: 'active',
  },
  {
    slug: 'he-business-tax-consultants',
    name: 'H&E Business and Tax Consultants LLC',
    category: 'professional-services',
    area: 'Niwot',
    description: 'Day-to-day accounting for small businesses.',
    sourceUrl: 'https://niwot.com/listing/he-business-and-tax-consultants-llc',
    schemaType: 'AccountingService',
    verifiedAt: AUDIT,
    status: 'active',
  },
  {
    slug: 'robinson-consulting',
    name: 'Robinson Consulting',
    category: 'professional-services',
    area: 'Niwot',
    description: 'Twenty years of consulting with small businesses across Boulder County.',
    sourceUrl: 'https://niwot.com/listing/robinson-consulting/',
    schemaType: 'ProfessionalService',
    verifiedAt: LINK_SWEEP,
    status: 'unverified',
    editorialNote:
      'Held back after the 2026-09-10 link sweep: the Association listing this row rested on now redirects to an unrelated site (iTrade Colorado), so the destination could not be stood behind. Restore it when the business can be traced to a current listing or a site of its own.',
  },
  {
    slug: 'noblestar-technologies',
    name: 'Noblestar Technologies LLC',
    category: 'professional-services',
    area: 'Niwot',
    description: 'Infrastructure and software for logistics, community development and operations.',
    sourceUrl: 'https://niwot.com/listing/noblestar-techologies-llc/',
    schemaType: 'ProfessionalService',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'dmr-group',
    name: 'DMR Group, LLC',
    category: 'professional-services',
    area: 'Niwot',
    sourceUrl: 'https://niwot.com/listing/dmr-group-llc/',
    schemaType: 'ProfessionalService',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'niwot-partners',
    name: 'Niwot Partners LLC',
    category: 'professional-services',
    area: 'Niwot',
    sourceUrl: 'https://niwot.com/listing/niwot-partners-llc/',
    schemaType: 'ProfessionalService',
    verifiedAt: AUDIT,
    status: 'active',
  },
  {
    slug: 'itrade-colorado',
    name: 'iTrade Colorado',
    category: 'professional-services',
    area: 'Niwot',
    description: 'Barter network: members earn credits on what they sell and spend them with other members.',
    sourceUrl: 'https://niwot.com/listing/itrade-colorado/',
    schemaType: 'ProfessionalService',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
  {
    slug: 'niwot-group-at-compass',
    name: 'The Niwot Group at Compass',
    category: 'professional-services',
    area: 'Old Town, Second Avenue',
    description: 'Residential real estate team on Second Avenue — Niwot Real Estate from 1986, part of Compass since July 2021. Co-hosts the Great Pumpkin Party.',
    website: 'https://theniwotgroup.com/',
    sourceUrl: 'https://niwot.com/listing/niwot-group-at-compass-formerly-niwot-real-estate/',
    schemaType: 'RealEstateAgent',
    verifiedAt: AUDIT,
    status: 'active',
    editorialNote:
      'Added in the September 2026 audit from the Association listing, the team’s own site and the Courier’s July 28, 2021 report on the Compass move. No source gives a house number, so only the street is published.',
  },

  /* ---- Stay the Night ---- */
  {
    slug: 'niwot-inn',
    name: 'Niwot Inn & Spa',
    category: 'stay-the-night',
    area: 'Old Town, Second Avenue',
    address: '342 Second Avenue',
    description: 'Fourteen rooms and an on-site spa, in the middle of Old Town.',
    website: 'https://niwotinn.com/',
    sourceUrl: 'https://niwotinn.com/',
    schemaType: 'Hotel',
    verifiedAt: FIRST_PASS,
    status: 'active',
  },
];

/* Validation runs on every import — the build, the tests and the browser
   checks all read this file — so a bad row fails loudly everywhere. The
   `today` used for the freshness check can be pinned with NIWOT_TODAY for
   reproducible builds. */
const today = process.env.NIWOT_TODAY || new Date().toISOString().slice(0, 10);
assertValidListings(records, { today });

const published = publishListings(records, CATEGORIES);

export default {
  ...published,
  records,
  freshnessDays: FRESHNESS_DAYS,
  categoryList: CATEGORIES,
};
